In [1]:
import numpy as np

In [2]:
def ForwardKinematics(joints):
    # simplified with WolframAlpha
    x = 3*np.sin(joints[0])*np.sin(joints[1])*np.cos(joints[2])*np.cos(joints[3]) + 3.5*np.sin(joints[0])*np.sin(joints[1])*np.cos(joints[2]) + 3*np.sin(joints[0])*np.cos(joints[1])*np.sin(joints[3])+ 3*np.cos(joints[0])*np.sin(joints[2])*np.cos(joints[3]) + 3.5*np.cos(joints[0])*np.sin(joints[2])
    y = -3*np.cos(joints[0])*np.sin(joints[1])*np.cos(joints[2])*np.cos(joints[3]) - 3.5*np.cos(joints[0])*np.sin(joints[1])*np.cos(joints[2]) - 3*np.cos(joints[0])*np.cos(joints[1])*np.sin(joints[3]) + 3*np.sin(joints[0])*np.sin(joints[2])*np.cos(joints[3]) + 3.5*np.sin(joints[0])*np.sin(joints[2])
    z = 3*np.cos(joints[1])*np.cos(joints[2])*np.cos(joints[3]) + 3.5*np.cos(joints[1])*np.cos(joints[2]) - 3*np.sin(joints[1])*np.sin(joints[3]) + 2.5
    EndEffector = np.array([x,y,z])
    return EndEffector


In [3]:
testdata = [[0.2, 0.4, 0.8, 0.5],
[0.2, 0.5, 0.8, 0.4],
[0.4, 0.5, 0.5, 0.5],
[0.4, 0.5, 0.5, 0.2],
[0.5, 0.2, 0.4, 0.8],
[0.5, 0.2, 0.5, 0.5],
[0.5, 0.5, 0.5, 0.5],
[1, 1, 1, 1],
[1, -1, 1, -1],
[-1, -1, -1, -1]]
fkresult = []
for i in range(10):
    fkresult.append(np.round(ForwardKinematics(testdata[i]),3))
fkresult = np.array(fkresult)
fkresult

array([[ 4.905, -2.055,  5.875],
       [ 5.023, -2.163,  5.769],
       [ 4.204, -2.394,  6.534],
       [ 4.103, -1.775,  7.174],
       [ 3.412, -1.705,  7.119],
       [ 3.769, -0.766,  7.489],
       [ 4.422, -1.962,  6.534],
       [ 5.435,  1.631,  1.871],
       [-0.779,  5.621,  1.871],
       [ 0.779,  5.621,  1.871]])

In [4]:
imageresult = np.array([[5.985, -3.131, 5.965],
[6.178, -3.287, 5.822],
[5.352, -3.461, 6.921],
[4.990, -2.535, 7.746],
[4.061, -2.304, 7.360],
[4.217, -1.093, 7.828],
[5.477, -2.940, 6.927],
[5.750, 2.579, 0.824],
[-0.845, 5.875, 2.012],
[0.930, 6.722, 1.945]])
imageresult

array([[ 5.985, -3.131,  5.965],
       [ 6.178, -3.287,  5.822],
       [ 5.352, -3.461,  6.921],
       [ 4.99 , -2.535,  7.746],
       [ 4.061, -2.304,  7.36 ],
       [ 4.217, -1.093,  7.828],
       [ 5.477, -2.94 ,  6.927],
       [ 5.75 ,  2.579,  0.824],
       [-0.845,  5.875,  2.012],
       [ 0.93 ,  6.722,  1.945]])

In [5]:
# comparing estimated positions
dist = []
for i in range(10):
    dist.append(np.linalg.norm(imageresult[i]-fkresult[i]))
print(np.round(dist,3))
mean = np.mean(dist)
print(np.round(mean,3))

[1.527 1.613 1.614 1.301 0.915 0.65  1.491 1.447 0.298 1.114]
1.197


In [6]:
# comparing estimated positions
diff = np.zeros(shape=(10,1))
k = 0 # 0, 1, 2 for x, y, z
for i in range(10):
#     print((fkresult[i][2]-imageresult[i][2]))
    diff[i] = np.round(((imageresult[i][k]-fkresult[i][k])), 3)
print(diff)
mean = np.mean(diff)
mean1 = np.mean(imageresult[:,k], axis = 0)
mean2 = np.mean(fkresult[:,k], axis = 0)
print("im pos mean ",np.round(mean1,3))
print("fk pos mean ",np.round(mean2,3))
print("mean diff ",np.round(mean,3))
print("% ", mean/(-mean1)*100)
print()

[[ 1.08 ]
 [ 1.155]
 [ 1.148]
 [ 0.887]
 [ 0.649]
 [ 0.448]
 [ 1.055]
 [ 0.315]
 [-0.066]
 [ 0.151]]
im pos mean  4.21
fk pos mean  3.527
mean diff  0.682
%  -16.206200261313693



In [7]:
def JacobianMatrix(joints):
    # calculated with WolframAlpha
    x0 = np.cos(joints[0])*(np.sin(joints[1])*np.cos(joints[2])*(3*np.cos(joints[3]) + 3.5) + 3*np.cos(joints[1])*np.sin(joints[3])) + np.sin(joints[0])*np.sin(joints[2])*(-3*np.cos(joints[3]) - 3.5)
    x1 = np.sin(joints[0])*(np.cos(joints[1])*np.cos(joints[2])*(3*np.cos(joints[3]) + 3.5) - 3*np.sin(joints[1])*np.sin(joints[3]))
    x2 = 0.5*(6*np.cos(joints[3]) + 7)*(np.cos(joints[0])*np.cos(joints[2]) - np.sin(joints[0])*np.sin(joints[1])*np.sin(joints[2]))
    x3 = np.sin(joints[0])*(3*np.cos(joints[1])*np.cos(joints[3]) - 3*np.sin(joints[1])*np.cos(joints[2])*np.sin(joints[3])) - 3*np.cos(joints[0])*np.sin(joints[2])*np.sin(joints[3])
    y0 = np.sin(joints[0])*(np.sin(joints[1])*np.cos(joints[2])*(3*np.cos(joints[3]) + 3.5) + 3*np.cos(joints[1])*np.sin(joints[3])) + np.cos(joints[0])*np.sin(joints[2])*(3*np.cos(joints[3]) + 3.5)
    y1 = np.cos(joints[0])*(np.cos(joints[1])*np.cos(joints[2])*(-3*np.cos(joints[3]) - 3.5) + 3*np.sin(joints[1])*np.sin(joints[3]))
    y2 = 0.5*(6*np.cos(joints[3]) + 7)*(np.cos(joints[0])*np.sin(joints[1])*np.sin(joints[2]) + np.sin(joints[0])*np.cos(joints[2]))
    y3 = -3*(-np.cos(joints[0])*np.sin(joints[1])*np.cos(joints[2])*np.sin(joints[3]) + np.cos(joints[0])*np.cos(joints[1])*np.cos(joints[3]) + np.sin(joints[0])*np.sin(joints[2])*np.sin(joints[3]))
    z0 = 0.0
    z1 = np.sin(joints[1])*np.cos(joints[2])*(-3*np.cos(joints[3]) - 3.5) - 3*np.cos(joints[1])*np.sin(joints[3])
    z2 = np.cos(joints[1])*np.sin(joints[2])*(-3*np.cos(joints[3]) - 3.5)
    z3 = -3*(np.cos(joints[1])*np.cos(joints[2])*np.sin(joints[3]) + np.sin(joints[1])*np.cos(joints[3]))

    jacobian = np.array([[x0,x1,x2,x3],[y0,y1,y2,y3],[z0,z1,z2,z3]])

    return jacobian

In [8]:
# JacobianMatrix([1,2,3,4])